// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VipPatientReport.Context;

#nullable disable

namespace VipPatientReport.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VipPatientReport.Models.M0301.M0301BenhNhanVip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GoiKham")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("IdChiNhanh")
                        .HasColumnType("bigint");

                    b.Property<string>("MaTiepNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaYTe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NamSinh")
                        .HasColumnType("int");

                    b.Property<string>("NguoiTiepNhan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PASSPORT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhongKham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenChuyenGia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ThoiGianTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdChiNhanh");

                    b.HasIndex("MaTiepNhan")
                        .IsUnique();

                    b.HasIndex("ThoiGianTiepNhan");

                    b.ToTable("Tien_Mau1");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CCCD = "07941778421",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-1",
                            HoTen = "Lê Văn Cường",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0001",
                            MaYTe = "MYT0001",
                            NamSinh = 1989,
                            NguoiTiepNhan = "NV004",
                            PASSPORT = "P5534812",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "GS. D",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 9, 14, 27, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2L,
                            CCCD = "07968937788",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-1",
                            HoTen = "Hoàng Văn Inh",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0002",
                            MaYTe = "MYT0002",
                            NamSinh = 1979,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P3043433",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 13, 11, 29, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 3L,
                            CCCD = "07957020252",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-1",
                            HoTen = "Đặng Văn Hoa",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0003",
                            MaYTe = "MYT0003",
                            NamSinh = 2000,
                            NguoiTiepNhan = "NV001",
                            PASSPORT = "P4939653",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 23, 15, 35, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 4L,
                            CCCD = "07987786202",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-1",
                            HoTen = "Trần Văn Kim",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0004",
                            MaYTe = "MYT0004",
                            NamSinh = 1992,
                            NguoiTiepNhan = "NV004",
                            PASSPORT = "P7059616",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 30, 7, 17, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 5L,
                            CCCD = "07961262825",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-3",
                            HoTen = "Bùi Văn Em",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0005",
                            MaYTe = "MYT0005",
                            NamSinh = 1995,
                            NguoiTiepNhan = "NV002",
                            PASSPORT = "P3003631",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 28, 11, 14, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 6L,
                            CCCD = "07981684565",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-3",
                            HoTen = "Vũ Văn Kim",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0006",
                            MaYTe = "MYT0006",
                            NamSinh = 1971,
                            NguoiTiepNhan = "NV003",
                            PASSPORT = "P9082703",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. A",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 5, 14, 18, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 7L,
                            CCCD = "07970936003",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-2",
                            HoTen = "Đặng Văn Hoa",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0007",
                            MaYTe = "MYT0007",
                            NamSinh = 1972,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P8177742",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 30, 12, 5, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 8L,
                            CCCD = "07999992295",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-3",
                            HoTen = "Nguyễn Văn Giang",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0008",
                            MaYTe = "MYT0008",
                            NamSinh = 1969,
                            NguoiTiepNhan = "NV001",
                            PASSPORT = "P1192776",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 7, 10, 55, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 9L,
                            CCCD = "07985394881",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-3",
                            HoTen = "Hoàng Văn Dung",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0009",
                            MaYTe = "MYT0009",
                            NamSinh = 1999,
                            NguoiTiepNhan = "NV001",
                            PASSPORT = "P7936903",
                            PhongKham = "PK201",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 22, 11, 24, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 10L,
                            CCCD = "07969148815",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-3",
                            HoTen = "Đặng Văn Phương",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0010",
                            MaYTe = "MYT0010",
                            NamSinh = 2000,
                            NguoiTiepNhan = "NV002",
                            PASSPORT = "P8164908",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 9, 7, 44, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 11L,
                            CCCD = "07932483656",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-3",
                            HoTen = "Đặng Văn Inh",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0011",
                            MaYTe = "MYT0011",
                            NamSinh = 1976,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P8463011",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. A",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 21, 7, 42, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 12L,
                            CCCD = "07936205692",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-2",
                            HoTen = "Nguyễn Văn Bình",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0012",
                            MaYTe = "MYT0012",
                            NamSinh = 1981,
                            NguoiTiepNhan = "NV002",
                            PASSPORT = "P4119342",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 2, 11, 55, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 13L,
                            CCCD = "07981122712",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-3",
                            HoTen = "Nguyễn Văn Em",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0013",
                            MaYTe = "MYT0013",
                            NamSinh = 1994,
                            NguoiTiepNhan = "NV004",
                            PASSPORT = "P4683604",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "GS. D",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 28, 7, 3, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 14L,
                            CCCD = "07979655503",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-2",
                            HoTen = "Lê Văn Bình",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0014",
                            MaYTe = "MYT0014",
                            NamSinh = 2001,
                            NguoiTiepNhan = "NV001",
                            PASSPORT = "P9214371",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 9, 10, 57, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 15L,
                            CCCD = "07944975597",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-1",
                            HoTen = "Võ Văn Em",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0015",
                            MaYTe = "MYT0015",
                            NamSinh = 1989,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P4921478",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "GS. D",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 27, 11, 24, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 16L,
                            CCCD = "07925637824",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-1",
                            HoTen = "Hoàng Văn Dung",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0016",
                            MaYTe = "MYT0016",
                            NamSinh = 1988,
                            NguoiTiepNhan = "NV001",
                            PASSPORT = "P5201121",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "GS. D",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 28, 12, 17, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 17L,
                            CCCD = "07930980729",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-3",
                            HoTen = "Hoàng Văn Bình",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0017",
                            MaYTe = "MYT0017",
                            NamSinh = 1984,
                            NguoiTiepNhan = "NV001",
                            PASSPORT = "P2862819",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 27, 14, 54, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 18L,
                            CCCD = "07938852846",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-1",
                            HoTen = "Vũ Văn Bình",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0018",
                            MaYTe = "MYT0018",
                            NamSinh = 1993,
                            NguoiTiepNhan = "NV004",
                            PASSPORT = "P8509029",
                            PhongKham = "PK201",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "GS. D",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 14, 8, 19, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 19L,
                            CCCD = "07933715035",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-3",
                            HoTen = "Vũ Văn Inh",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0019",
                            MaYTe = "MYT0019",
                            NamSinh = 1992,
                            NguoiTiepNhan = "NV003",
                            PASSPORT = "P2185979",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 11, 9, 35, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 20L,
                            CCCD = "07914692435",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-3",
                            HoTen = "Bùi Văn Em",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0020",
                            MaYTe = "MYT0020",
                            NamSinh = 1977,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P9425542",
                            PhongKham = "PK201",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. A",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 27, 8, 22, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 21L,
                            CCCD = "07958899935",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-2",
                            HoTen = "Võ Văn Phương",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0021",
                            MaYTe = "MYT0021",
                            NamSinh = 1975,
                            NguoiTiepNhan = "NV004",
                            PASSPORT = "P2808506",
                            PhongKham = "PK201",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 27, 9, 43, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 22L,
                            CCCD = "07962555075",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-1",
                            HoTen = "Đặng Văn Kim",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0022",
                            MaYTe = "MYT0022",
                            NamSinh = 1973,
                            NguoiTiepNhan = "NV001",
                            PASSPORT = "P2685513",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "GS. D",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 7, 15, 59, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 23L,
                            CCCD = "07937920079",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-3",
                            HoTen = "Võ Văn Kim",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0023",
                            MaYTe = "MYT0023",
                            NamSinh = 1993,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P9475950",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 3, 7, 42, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 24L,
                            CCCD = "07952981771",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-2",
                            HoTen = "Đinh Văn Hoa",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0024",
                            MaYTe = "MYT0024",
                            NamSinh = 1962,
                            NguoiTiepNhan = "NV002",
                            PASSPORT = "P8633214",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. A",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 29, 14, 13, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 25L,
                            CCCD = "07926088889",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-3",
                            HoTen = "Bùi Văn Inh",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0025",
                            MaYTe = "MYT0025",
                            NamSinh = 1989,
                            NguoiTiepNhan = "NV003",
                            PASSPORT = "P3351942",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 15, 16, 40, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 26L,
                            CCCD = "07929966675",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-2",
                            HoTen = "Nguyễn Văn Phương",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0026",
                            MaYTe = "MYT0026",
                            NamSinh = 1983,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P3956087",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 14, 8, 55, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 27L,
                            CCCD = "07928388425",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-1",
                            HoTen = "Trần Văn Giang",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0027",
                            MaYTe = "MYT0027",
                            NamSinh = 1968,
                            NguoiTiepNhan = "NV001",
                            PASSPORT = "P6449548",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "GS. D",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 30, 13, 22, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 28L,
                            CCCD = "07925477322",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-1",
                            HoTen = "Đặng Văn Kim",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0028",
                            MaYTe = "MYT0028",
                            NamSinh = 1992,
                            NguoiTiepNhan = "NV002",
                            PASSPORT = "P9592753",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 21, 9, 24, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 29L,
                            CCCD = "07986660738",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-2",
                            HoTen = "Vũ Văn An",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0029",
                            MaYTe = "MYT0029",
                            NamSinh = 1978,
                            NguoiTiepNhan = "NV002",
                            PASSPORT = "P9313423",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. A",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 5, 13, 58, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 30L,
                            CCCD = "07929523621",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-2",
                            HoTen = "Võ Văn Phương",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0030",
                            MaYTe = "MYT0030",
                            NamSinh = 1963,
                            NguoiTiepNhan = "NV002",
                            PASSPORT = "P6815352",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 15, 16, 4, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 31L,
                            CCCD = "07919769542",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-1",
                            HoTen = "Lê Văn Hoa",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0031",
                            MaYTe = "MYT0031",
                            NamSinh = 1980,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P5697183",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 30, 9, 57, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 32L,
                            CCCD = "07978364602",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-1",
                            HoTen = "Võ Văn Bình",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0032",
                            MaYTe = "MYT0032",
                            NamSinh = 1968,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P4323146",
                            PhongKham = "PK201",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. A",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 28, 7, 29, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 33L,
                            CCCD = "07976789511",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-2",
                            HoTen = "Nguyễn Văn Dung",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0033",
                            MaYTe = "MYT0033",
                            NamSinh = 1999,
                            NguoiTiepNhan = "NV003",
                            PASSPORT = "P7080740",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 18, 15, 16, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 34L,
                            CCCD = "07911890562",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-2",
                            HoTen = "Võ Văn An",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0034",
                            MaYTe = "MYT0034",
                            NamSinh = 1990,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P7655434",
                            PhongKham = "PK201",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 19, 13, 47, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 35L,
                            CCCD = "07958190550",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-1",
                            HoTen = "Võ Văn Cường",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0035",
                            MaYTe = "MYT0035",
                            NamSinh = 1997,
                            NguoiTiepNhan = "NV003",
                            PASSPORT = "P6184140",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. A",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 13, 10, 22, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 36L,
                            CCCD = "07991917547",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-3",
                            HoTen = "Trần Văn An",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0036",
                            MaYTe = "MYT0036",
                            NamSinh = 2003,
                            NguoiTiepNhan = "NV001",
                            PASSPORT = "P3242602",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 28, 11, 7, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 37L,
                            CCCD = "07936171267",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-2",
                            HoTen = "Đặng Văn Kim",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0037",
                            MaYTe = "MYT0037",
                            NamSinh = 1971,
                            NguoiTiepNhan = "NV004",
                            PASSPORT = "P3885682",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. A",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 7, 13, 6, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 38L,
                            CCCD = "07958765793",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-2",
                            HoTen = "Vũ Văn An",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0038",
                            MaYTe = "MYT0038",
                            NamSinh = 2000,
                            NguoiTiepNhan = "NV004",
                            PASSPORT = "P9929893",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. A",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 3, 16, 12, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 39L,
                            CCCD = "07929461177",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-3",
                            HoTen = "Hoàng Văn Cường",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0039",
                            MaYTe = "MYT0039",
                            NamSinh = 1966,
                            NguoiTiepNhan = "NV003",
                            PASSPORT = "P8453487",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 27, 8, 26, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 40L,
                            CCCD = "07950334146",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-1",
                            HoTen = "Đinh Văn An",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0040",
                            MaYTe = "MYT0040",
                            NamSinh = 2000,
                            NguoiTiepNhan = "NV004",
                            PASSPORT = "P1705111",
                            PhongKham = "PK201",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "GS. D",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 22, 9, 26, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 41L,
                            CCCD = "07975763098",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-2",
                            HoTen = "Nguyễn Văn Bình",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0041",
                            MaYTe = "MYT0041",
                            NamSinh = 1976,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P4497383",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 12, 10, 5, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 42L,
                            CCCD = "07946455374",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-1",
                            HoTen = "Hoàng Văn Giang",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0042",
                            MaYTe = "MYT0042",
                            NamSinh = 2004,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P3901036",
                            PhongKham = "PK201",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 10, 11, 4, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 43L,
                            CCCD = "07969151576",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-2",
                            HoTen = "Vũ Văn Inh",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0043",
                            MaYTe = "MYT0043",
                            NamSinh = 1983,
                            NguoiTiepNhan = "NV003",
                            PASSPORT = "P4791189",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 12, 15, 40, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 44L,
                            CCCD = "07928101709",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-2",
                            HoTen = "Phạm Văn Em",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0044",
                            MaYTe = "MYT0044",
                            NamSinh = 1969,
                            NguoiTiepNhan = "NV001",
                            PASSPORT = "P6850937",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 24, 8, 5, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 45L,
                            CCCD = "07961565971",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-2",
                            HoTen = "Hoàng Văn Cường",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0045",
                            MaYTe = "MYT0045",
                            NamSinh = 1999,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P4637583",
                            PhongKham = "PK102",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 15, 11, 9, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 46L,
                            CCCD = "07914015557",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-2",
                            HoTen = "Vũ Văn Cường",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0046",
                            MaYTe = "MYT0046",
                            NamSinh = 1980,
                            NguoiTiepNhan = "NV002",
                            PASSPORT = "P5944033",
                            PhongKham = "PK201",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. A",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 23, 12, 54, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        },
                        new
                        {
                            Id = 47L,
                            CCCD = "07962916562",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-2",
                            HoTen = "Bùi Văn Inh",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0047",
                            MaYTe = "MYT0047",
                            NamSinh = 1967,
                            NguoiTiepNhan = "NV005",
                            PASSPORT = "P4667606",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. A",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 5, 10, 32, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 48L,
                            CCCD = "07990829155",
                            GioiTinh = "Nam",
                            GoiKham = "VIP-2",
                            HoTen = "Trần Văn Hoa",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0048",
                            MaYTe = "MYT0048",
                            NamSinh = 2000,
                            NguoiTiepNhan = "NV004",
                            PASSPORT = "P7897582",
                            PhongKham = "PK201",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "GS. D",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 30, 15, 32, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 49L,
                            CCCD = "07986154858",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-3",
                            HoTen = "Đinh Văn Em",
                            IdChiNhanh = 1L,
                            MaTiepNhan = "MTN0049",
                            MaYTe = "MYT0049",
                            NamSinh = 1973,
                            NguoiTiepNhan = "NV003",
                            PASSPORT = "P3378577",
                            PhongKham = "PK202",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. B",
                            ThoiGianTiepNhan = new DateTime(2025, 7, 20, 13, 15, 0, 0, DateTimeKind.Local),
                            TrangThai = true
                        },
                        new
                        {
                            Id = 50L,
                            CCCD = "07947695523",
                            GioiTinh = "Nữ",
                            GoiKham = "VIP-3",
                            HoTen = "Vũ Văn Bình",
                            IdChiNhanh = 2L,
                            MaTiepNhan = "MTN0050",
                            MaYTe = "MYT0050",
                            NamSinh = 1975,
                            NguoiTiepNhan = "NV003",
                            PASSPORT = "P6549769",
                            PhongKham = "PK101",
                            QuocTich = "Việt Nam",
                            TenChuyenGia = "BS. C",
                            ThoiGianTiepNhan = new DateTime(2025, 8, 8, 15, 35, 0, 0, DateTimeKind.Local),
                            TrangThai = false
                        });
                });

            modelBuilder.Entity("VipPatientReport.Models.M0301.M0301ThongTinDoanhNghiep", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IDChiNhanh")
                        .HasColumnType("bigint")
                        .HasColumnName("IDChiNhanh");

                    b.Property<string>("MaCSKCB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCSKCB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ThongTinDoanhNghiep");
                });
#pragma warning restore 612, 618
        }
    }
}
